#!/usr/bin/python

import daemon
import os
import signal
import sys

import tornado.options

from pakfire.buildservice.web import Application

#tornado.options.parse_command_line()

if __name__ == "__main__":
	app = Application()

	context = daemon.DaemonContext(
		working_directory=os.getcwd(),
#		stdout=sys.stdout, stderr=sys.stderr, # XXX causes errors...
	)

	context.signal_map = {
		signal.SIGHUP  : app.reload,
		signal.SIGTERM : app.shutdown,
	}

#	with context:
#		app.run()

	app.run()
