#!/usr/bin/python

import tornado.ioloop
import tornado.options

import pakfire.buildservice.web

tornado.options.define("debug", type=bool, default=False, help="Enable debug mode")
tornado.options.define("port", type=int, default=9000, help="Port to listen on")

def run():
	tornado.options.parse_command_line()

	# Initialise application
	app = pakfire.buildservice.web.Application(debug=tornado.options.options.debug)
	app.listen(tornado.options.options.port, xheaders=True)

	# Launch IOLoop
	tornado.ioloop.IOLoop.current().start()

run()
