#!/usr/bin/python

import pakfire.buildservice
import pakfire.buildservice.manager

# Use tornado's logging options.
import tornado.options
tornado.options.parse_command_line()

# main

# Create Scheduler instance.
s = pakfire.buildservice.scheduler.Scheduler()

# Create Pakfire instance.
p = pakfire.buildservice.Pakfire()

events = (
	pakfire.buildservice.manager.BuildsFailedRestartEvent,
	pakfire.buildservice.manager.CheckBuildDependenciesEvent,
	pakfire.buildservice.manager.DistEvent,
	pakfire.buildservice.manager.RepositoriesUpdateEvent,
)

# Add all events to the scheduler.
for e in events:
	i = e(p)
	s.add_event(i)

# Run the scheduler.
s.run()
