#!/usr/bin/python

import backend.main
import backend.scheduler

import manager

# Use tornado's logging options.
import tornado.options
tornado.options.parse_command_line()

# main

# Create Scheduler instance.
s = backend.scheduler.Scheduler()

# Create Pakfire instance.
p = backend.main.Pakfire()

events = (
	manager.BugsUpdateEvent,
	manager.BuildsFailedRestartEvent,
	manager.CheckBuildDependenciesEvent,
	manager.CleanupFilesEvent,
	manager.CreateTestBuildsEvent,
	manager.DistEvent,
	manager.MessagesSendEvent,
	manager.RepositoriesUpdateEvent,
	manager.SessionsCleanupEvent,
	manager.SourcesPullEvent,
	manager.UploadsCleanupEvent,
)

# Add all events to the scheduler.
for e in events:
	i = e(p)
	s.add_event(i)

# Run the scheduler.
s.run()
